support windows non-console mode.  include Gauche-gl to windows installer
git-svn-id: https://gauche.svn.sourceforge.net/svnroot/gauche/Gauche/trunk@7239 c205566b-fb4e-0410-ab5c-8f0660156277

diff --git a/DIST b/DIST
--- a/DIST
+++ b/DIST
@@ -180,47 +180,45 @@ if [ "$rpm" = "yes" ]; then
 fi
 
 #
-# MinGW specific packager
+# MinGW specific packager.  As of 0.9.1, Gauche can self build with MinGW+MSYS
 #
 if [ "$mingw" = "yes" ]; then
-  mingwdir=${MINGWDIR:-/cygdrive/c/mingw}
-  cyggosh=${CYGGOSH:-/usr/local/bin/gosh}
-
-  PATH=$mingwdir/bin:$PATH
   case `gcc --version` in
     *mingw*) ;;
-    *) echo "Set PATH to have MinGW bin directory first"
+    *) echo "gcc isn't for mingw.  make sure you're executing this on MinGW+MSYS."
        exit 1;;
   esac
-  maintainer_clean
+
+  if [ -d ../Gauche-gl ]; then
+    echo "Found Gauche-gl."
+  else
+    echo "Cannot find ../Gauche-gl.  Aborting."
+    exit 1
+  fi
+
   makensis_path=`which makensis.exe 2> /dev/null`
   if test -e "$makensis_path"; then
       echo "NSIS compiler exists: $makensis_path"
       (cd winnt/nsis; make clean)
   fi
-  distdir=`pwd`/../Gauche-mingw-dist
+  distdir=`pwd`/../Gauche-mingw-dist/Gauche
   rm -rf $distdir
+  maintainer_clean
   ./DIST gen
-  ./configure --build=i686-pc-mingw32 --prefix=$distdir/Gauche
+  ./configure --prefix=$distdir
   check_version
   make
-  # use Cygwin's gosh to install stuff
-  make GOSH=$cyggosh install
-  (cd src; make GOSH=$cyggosh install-mingw)
-  rm -rf $distdir/Gauche/bin/gauche-install
-  rm -rf $distdir/Gauche/bin/gauche-package
-  rm -rf $distdir/Gauche/bin/gauche-config
-  rm -rf $distdir/Gauche/bin/gauche-cesconv
-  rm -rf $distdir/Gauche/lib/libgauche.dll*
-  rm -rf $distdir/Gauche/lib/gauche/$VERSION/*/gosh.exe
-  rm -rf $distdir/Gauche/lib/gauche/$VERSION/*/libgauche.dll
-  cp COPYING $distdir/Gauche
-  cp $mingwdir/bin/mingwm10.dll $distdir/Gauche/bin
-  (cd $distdir; zip -r Gauche-mingw-$VERSION.zip Gauche)
+  make install
+  cp COPYING $distdir
+  cp /c/MinGW/bin/mingwm10.dll $distdir/bin
+
+  PATH=$distdir/bin:$PATH
+  (cd ../Gauche-gl; ./DIST gen; ./configure --prefix=$distdir --with-glut=mingw-static; make clean; make; make install)
+
+#  (cd $distdir; zip -r Gauche-mingw-$VERSION.zip Gauche)
   if test -e "$makensis_path"; then
-      echo "NSIS compiler exists: $makensis_path"
-      cd winnt/nsis
-      make
+     cd winnt/nsis
+     make
   fi
 fi
 
